services:
  - type: web
    name: bgmiserver
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_TOKEN
        sync: false
      - key: APP_ID
        value: PUBG
      - key: CORS_ORIGIN
        value: '*'
      - key: PANEL_LICENSE
        value: Vm8Lk7Uj2JmsjCPVPVjrLa7zgfx3uz9E
